site_name: Hyblock Capital SDK
site_description: SDK no oficial de Python para la API de Hyblock Capital
site_url: https://ljofreflor.github.io/hyblock-capital-sdk/
repo_url: https://github.com/ljofreflor/hyblock-capital-sdk
repo_name: ljofreflor/hyblock-capital-sdk
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - Installation: installation.md
  - Quick Start: quickstart.md
  - API Reference:
    - Client: api/client.md
    - Liquidity API: api/liquidity.md
    - Catalog API: api/catalog.md
    - Funding Rate API: api/funding-rate.md
    - Longs and Shorts API: api/longs-shorts.md
    - Open Interest API: api/open-interest.md
    - Options API: api/options.md
    - Orderbook API: api/orderbook.md
    - Orderflow API: api/orderflow.md
    - Profile Tool API: api/profile-tool.md
    - Sentiment API: api/sentiment.md
    - Models: api/models.md
    - Exceptions: api/exceptions.md
  - Examples:
    - Basic Usage: examples/basic-usage.md
    - Liquidation Pools: examples/liquidation-pools.md
    - Liquidation with Leverage: examples/liquidation-leverage.md
  - Development:
    - Contributing: development/contributing.md
    - Building from Source: development/building.md
    - SDK Generation: development/sdk-generation.md
  - About:
    - License: about/license.md
    - Changelog: about/changelog.md

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ljofreflor/hyblock-capital-sdk
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/hyblock-capital-sdk/