name: Branch Policy

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  enforce-branch-policy:
    name: Enforce Branch Policy
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.event_name == 'push'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Validate PR policies
        if: github.event_name == 'pull_request'
        env:
          HEAD_REF: ${{ github.head_ref }}
          BASE_REF: ${{ github.event.pull_request.base.ref }}
        run: |
          echo "🔍 Validando política de ramas..."
          echo "Base: $BASE_REF | Head: $HEAD_REF"
          
          # Validar PR a main solo desde develop
          if [ "$BASE_REF" = "main" ] && [ "$HEAD_REF" != "develop" ]; then
            echo "❌ [POLICY VIOLATION] Solo se permiten PRs a main desde la rama 'develop'."
            echo "❌ Rama origen: $HEAD_REF (debe ser 'develop')"
            echo "❌ Rama destino: $BASE_REF"
            exit 1
          fi
          
          # Validar PR a develop solo desde feature/fix branches
          if [ "$BASE_REF" = "develop" ]; then
            if [[ "$HEAD_REF" != feature/* && "$HEAD_REF" != fix/* && "$HEAD_REF" != hotfix/* ]]; then
              echo "❌ [POLICY VIOLATION] Solo se permiten PRs a develop desde ramas 'feature/*', 'fix/*' o 'hotfix/*'."
              echo "❌ Rama origen: $HEAD_REF (debe ser feature/*, fix/* o hotfix/*)"
              echo "❌ Rama destino: $BASE_REF"
              exit 1
            fi
          fi
          
          echo "✅ [POLICY] Regla de ramas cumplida - PR desde $HEAD_REF a $BASE_REF"
      
      - name: Block direct push to protected branches
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "❌ [POLICY VIOLATION] Push directo a main no permitido."
            echo "❌ Solo se permiten PRs desde develop que pasen los tests unitarios."
            echo "❌ Usa: git push origin develop y crea un PR"
          elif [ "${{ github.ref }}" = "refs/heads/develop" ]; then
            echo "❌ [POLICY VIOLATION] Push directo a develop no permitido."
            echo "❌ Solo se permiten PRs desde ramas feature/*, fix/* o hotfix/*."
            echo "❌ Usa: git push origin feature/tu-feature y crea un PR"
          fi
          exit 1
      
      - name: Run unit tests for PR validation
        if: github.event_name == 'pull_request' && (github.base_ref == 'main' || github.base_ref == 'develop')
        run: |
          echo "🧪 Ejecutando tests unitarios para validar PR..."
          
          # Verificar que Python esté disponible
          python --version || python3 --version
          
          # Verificar que Poetry esté disponible
          poetry --version
          
          # Instalar dependencias
          poetry install --with dev
          
          # Ejecutar tests unitarios
          echo "🔍 Ejecutando tests unitarios..."
          poetry run pytest tests/ -v --tb=short
          
          echo "✅ Tests unitarios pasaron exitosamente"
      
      - name: Validate PR requirements
        if: github.event_name == 'pull_request' && (github.base_ref == 'main' || github.base_ref == 'develop')
        run: |
          echo "📋 Validando requisitos del PR..."
          
          # Verificar que el PR tenga descripción
          if [ -z "${{ github.event.pull_request.body }}" ]; then
            echo "⚠️  Advertencia: El PR no tiene descripción"
          else
            echo "✅ PR tiene descripción"
          fi
          
          # Verificar que no sea un draft
          if [ "${{ github.event.pull_request.draft }}" = "true" ]; then
            echo "❌ [POLICY] No se permiten PRs en draft a ramas protegidas"
            exit 1
          fi
          
          echo "✅ PR cumple con los requisitos básicos"


